"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var index_1 = require("type-assertions/index");
var index_2 = require("./index");
var mapResult1 = (0, index_2.map)()(String)()([1, 2, 3]);
(0, index_1.typeAssert)();
var mapResult2 = (0, index_2.map)(Boolean, [1, 0, 1]);
(0, index_1.typeAssert)();
var reduceResult1 = (0, index_2.reduce)()(function (a, b) { return a + b; })()(0)()([1, 2, 3]);
(0, index_1.typeAssert)();
var reduceResult2 = (0, index_2.reduce)(index_2.add, 0, [1, 2, 3]);
(0, index_1.typeAssert)();
var reduceResult3 = (0, index_2.reduce)(index_2.subtract, 0, [1, 2, 3]);
(0, index_1.typeAssert)();
var reduceResult4 = (0, index_2.reduce)(function (a, b) { return a + b; }, '', ['1', '2', '3']);
(0, index_1.typeAssert)();
var filterResult1 = (0, index_2.filter)()(function (n) { return n !== 0; })()([0, 1, 2]);
(0, index_1.typeAssert)();
var filterResult2 = (0, index_2.filter)(Boolean, [0, 1, 2]);
(0, index_1.typeAssert)();
var addResult1 = (0, index_2.add)()(1)()(2);
(0, index_1.typeAssert)();
var addResult2 = (0, index_2.add)(1, 2);
(0, index_1.typeAssert)();
var subtractResult1 = (0, index_2.subtract)()(2)()(1);
(0, index_1.typeAssert)();
var subtractResult2 = (0, index_2.subtract)(2, 1);
(0, index_1.typeAssert)();
var propResult1 = (0, index_2.prop)()('x')()({ x: 1, y: 'Hello' });
(0, index_1.typeAssert)();
var propResult2 = (0, index_2.prop)('y', { x: 1, y: 'Hello' });
(0, index_1.typeAssert)();
var pipeResult1 = (0, index_2.pipe)((0, index_2.filter)(Boolean), (0, index_2.map)(String), (0, index_2.reduce)(function (a, b) { return a + b; }, ''))([0, 1, 2, 3]);
(0, index_1.typeAssert)();
var pipeResult2 = (0, index_2.pipe)()()((0, index_2.filter)(Boolean), (0, index_2.map)(String))([0, 1, 2, 3]);
(0, index_1.typeAssert)();
